server:
    error:
        include-stacktrace: never
        include-message: never
        include-binding-errors: never

spring:
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false
        open-in-view: false

logging:
    level:
        org.springframework.web: WARN
        org.hibernate: WARN
        win.pluvivanto.roombook: INFO

management:
    endpoints:
        web:
            exposure:
                include: health,info
    endpoint:
        health:
            show-details: never